# Generated by Django 3.1.4 on 2020-12-29 11:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('diary', '0001_initial'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='mood',
            name='Score value is valid between 1 and 5',
        ),
        migrations.AddConstraint(
            model_name='mood',
            constraint=models.CheckConstraint(check=models.Q(('score__gte', 1), ('score__lte', 5)), name='score constraint'),
        ),
    ]
