# Generated by Django 3.1.4 on 2020-12-29 12:40

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('diary', '0002_auto_20201229_1203'),
    ]

    operations = [
        migrations.AddField(
            model_name='mood',
            name='created_on',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
