# Generated by Django 3.1.4 on 2020-12-29 12:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('diary', '0003_mood_created_on'),
    ]

    operations = [
        migrations.AddField(
            model_name='mood',
            name='name',
            field=models.CharField(default='pepe', max_length=50),
            preserve_default=False,
        ),
    ]
