# Generated by Django 3.1.4 on 2020-12-29 19:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('diary', '0004_mood_name'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='mood',
            name='created_on',
        ),
        migrations.AddField(
            model_name='mood',
            name='updated_on',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
