# Generated by Django 3.1.4 on 2021-01-02 21:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('diary', '0006_profile'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='avatar',
            field=models.ImageField(blank=True, upload_to='diary/avatars'),
        ),
    ]
