# Generated by Django 3.1.4 on 2021-01-20 20:59

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('diary', '0015_auto_20210118_2250'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mood',
            name='updated_on',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
