# Generated by Django 3.1.4 on 2021-01-23 19:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('diary', '0016_auto_20210120_2159'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='public',
            field=models.BooleanField(default=False),
        ),
    ]
