# Generated by Django 3.1.4 on 2021-02-01 17:29

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('diary', '0018_advice'),
    ]

    operations = [
        migrations.AddField(
            model_name='advice',
            name='likes',
            field=models.IntegerField(default=23),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='advice',
            name='user',
            field=models.ForeignKey(default=32, on_delete=django.db.models.deletion.CASCADE, to='auth.user'),
            preserve_default=False,
        ),
    ]
